"""Load-bearing native lifetime instrument checks; no mutation writes files."""

from _mutations import run

MODULE = "tests.native_lifecycle:"
TEST = "tests/test_native_lifecycle.py::"
CUSTODY = "tests/runtime/test_ownership_loss_custody.py::"

MUTANTS = (
    ("unentered close disposes", MODULE + "NativeFixtureProvider.close",
     "if handle.entered:", "if True:",
     TEST + "test_native_acquire_and_unentered_close_write_nothing"),
    ("durable absent resource not fenced", MODULE + "NativeFixtureProvider.reconcile",
     "await dispose_acquisition(self.closure, AcquisitionPaths(self.root, acquisition))", "pass",
     TEST + "test_native_recovery_disposes_durable_row_even_if_absent"),
    ("foreign root accepted", MODULE + "NativeFixtureProvider.reconcile",
     "row.resource_ref != self.reference(acquisition)", "False",
     TEST + "test_native_recovery_rejects_foreign_rows[root]"),
    ("current epoch reconciled", MODULE + "NativeFixtureProvider.reconcile",
     "row.acquisition_epoch >= context.run_lease.epoch", "False",
     TEST + "test_native_recovery_rejects_foreign_rows[epoch]"),
    ("foreign binding accepted", MODULE + "NativeFixtureProvider.reconcile",
     "row.binding_id != context.binding.binding", "False",
     TEST + "test_native_recovery_rejects_foreign_rows[binding]"),
    ("foreign path accepted", MODULE + "NativeFixtureProvider.reconcile",
     "row.path != context.path", "False",
     TEST + "test_native_recovery_rejects_foreign_rows[path]"),
    ("control not observed", MODULE + "NativeFixture.check_control",
     "self.context.check_control()", "pass",
     TEST + "test_native_work_observes_control_and_closure"),
    ("closure not observed", MODULE + "NativeFixture.require_open",
     "self.provider.closure.require_open, self.paths", "lambda _: None, self.paths",
     TEST + "test_native_work_observes_control_and_closure"),
    ("closure not checked under guard", MODULE + "NativeFixture.exchange",
     "await self.require_open()", "pass",
     TEST + "test_native_checks_closure_after_guard_before_endpoint"),
    ("borrowed guard not inherited", "tests.substrate.test_linux_duplex:exchange",
     "guard_fds=(guard,)", "guard_fds=()",
     TEST + "test_duplex_fixture_borrows_recorded_guard_without_relocking"),
    ("fixture route falsely granted network none", MODULE + "assemble",
     '"network": "allow"', '"network": "none"',
     TEST + "test_fixture_graph_admits_without_a_production_executor_profile"),
    ("failed worker process discarded", MODULE + "NativeFixture.worker",
     'evidence["process"] = {**asdict(result),', 'evidence["discarded"] = {**asdict(result),',
     TEST + "test_native_worker_retains_complete_failure_before_asserting"),
    ("failed exchange result discarded", MODULE + "NativeFixture.worker",
     "result = exc.result", "pass",
     TEST + "test_native_worker_retains_complete_failure_before_asserting[True]"),
    ("failed worker decoding discarded", MODULE + "NativeFixture.worker",
     'evidence["decoded"] = decoded.model_dump(mode="json")', 'pass',
     TEST + "test_native_worker_retains_complete_failure_before_asserting"),
    ("local closure missed across await", MODULE + "NativeFixture.require_open",
     ")))\n    self.check_control()", ")))\n    pass",
     TEST + "test_native_local_close_during_closure_check_refuses"),
    ("supervisor credited as session-changing worker",
     "tests.substrate._native_recovery_owner:physical_snapshot",
     'args == [b"/usr/bin/python3", b"-I", b"-c", WORKER.encode(), b""]',
     "WORKER.encode() in args",
     TEST + "test_native_process_observer_distinguishes_worker_child_from_supervisors"),
    ("worker parent credited without session change",
     "tests.substrate._native_recovery_owner:physical_snapshot",
     "os.getsid(pid) == pid", "True",
     TEST + "test_native_process_observer_distinguishes_worker_child_from_supervisors"),
    ("cancellation closes an observed lost owner's recorded acquisitions",
     "constructicon.runtime.walker:Walker._invoke",
     "if lost:\n            raise lost[0] from",
     "if False:\n            raise lost[0] from",
     "tests/runtime/test_materialization_control.py::"
     "test_cancellation_during_ownership_loss_teardown_leaves_recorded_siblings_to_successor"),
    ("an observed ownership loss relinquishes local custody",
     "constructicon.runtime.walker:Walker._invoke",
     "failure := await self._relinquish_acquired(acquired)", "failure := None",
     CUSTODY + "test_a_live_loser_releases_custody_so_its_successor_can_reconcile[checked]"),
    ("a latched ownership loss relinquishes local custody",
     "constructicon.runtime.walker:Walker._invoke",
     "raise lost[0] from await self._relinquish_acquired(acquired)", "raise lost[0] from None",
     CUSTODY + "test_a_live_loser_releases_custody_so_its_successor_can_reconcile[cancelled]"),
    ("one failed relinquishment strands no sibling",
     "constructicon.runtime.walker:Walker._relinquish_acquired",
     "errors.append(exc)", "raise",
     CUSTODY + "test_one_failed_relinquishment_strands_no_sibling_and_the_loss_stays_primary"),
    ("a cancellation during relinquishment cannot displace the loss",
     "constructicon.runtime.walker:Walker._relinquish_acquired",
     "with contextlib.suppress(asyncio.CancelledError):", "with contextlib.suppress():",
     CUSTODY + "test_a_cancellation_during_relinquishment_leaves_the_loss_primary"),
    ("a loss found while closing relinquishes the rest",
     "constructicon.runtime.walker:Walker._close_acquired",
     "failure := await self._relinquish_acquired(rest)", "failure := None",
     CUSTODY + "test_a_loss_found_while_closing_relinquishes_the_siblings_not_yet_closed"),
)

if __name__ == "__main__":
    raise SystemExit(run(MUTANTS))
